package com.example.tax_payment.infrastructure.pdf;

import com.example.tax_payment.application.port.outbound.InvoicePdfPort;
import com.example.tax_payment.domain.model.Invoice;
import com.lowagie.text.Document;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfWriter;
import org.springframework.stereotype.Component;

import java.io.ByteArrayOutputStream;

@Component
public class OpenPdfInvoiceAdapter implements InvoicePdfPort {

    @Override
    public byte[] generate(Invoice invoice) {

        try (ByteArrayOutputStream outputStream = new ByteArrayOutputStream()) {

            Document document = new Document();
            PdfWriter.getInstance(document, outputStream);

            document.open();

            // =========================
            // HEADER
            // =========================
            document.add(new Paragraph("TAX INVOICE"));
            document.add(new Paragraph(" "));

            document.add(new Paragraph("Invoice Number: " + invoice.getInvoiceNumber()));
            document.add(new Paragraph("Invoice ID: " + invoice.getId()));
            document.add(new Paragraph("Status: " + invoice.getStatus()));
            document.add(new Paragraph("Taxpayer TIN: " + invoice.getTaxpayerTin()));
            document.add(new Paragraph(" "));

            // =========================
            // TAX INFO
            // =========================
            document.add(new Paragraph("TAX INFORMATION"));
            document.add(new Paragraph("Tax Type: " + invoice.getTaxType()));
            document.add(new Paragraph("Tax Period: " + invoice.getTaxPeriod()));
            document.add(new Paragraph("Currency: " + invoice.getCurrency()));
            document.add(new Paragraph(" "));

            // =========================
            // FINANCIAL BREAKDOWN
            // =========================
            document.add(new Paragraph("FINANCIAL SUMMARY"));

            document.add(new Paragraph("Principal Amount: " + invoice.getPrincipalAmount()));
            document.add(new Paragraph("Interest Amount: " + invoice.getInterestAmount()));
            document.add(new Paragraph("Penalty Amount: " + invoice.getPenaltyAmount()));

            document.add(new Paragraph(" "));

            document.add(new Paragraph("Paid Principal: " + invoice.getTotalPaidPrincipal()));
            document.add(new Paragraph("Paid Interest: " + invoice.getTotalPaidInterest()));
            document.add(new Paragraph("Paid Penalty: " + invoice.getTotalPaidPenalty()));

            document.add(new Paragraph(" "));

            document.add(new Paragraph("Outstanding Principal: " + invoice.getOutstandingPrincipal()));
            document.add(new Paragraph("Outstanding Interest: " + invoice.getOutstandingInterest()));
            document.add(new Paragraph("Outstanding Penalty: " + invoice.getOutstandingPenalty()));

            document.add(new Paragraph(" "));

            document.add(new Paragraph("TOTAL OUTSTANDING: " + invoice.getTotalOutstanding()));

            // =========================
            // FOOTER
            // =========================
            document.add(new Paragraph(" "));
            document.add(new Paragraph("Generated by Tax Payment System"));

            document.close();

            return outputStream.toByteArray();

        } catch (Exception e) {
            throw new RuntimeException("Failed to generate invoice PDF", e);
        }
    }
}